#!/usr/bin/env bun
import * as fs from 'node:fs';
import * as path from 'node:path';

const buildDir = path.join(process.cwd(), 'dist/client');
const flattened: string[] = [];

function flatten(dir: string): void {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === 'assets') continue;
    const child = path.join(dir, entry.name);
    flatten(child);
    const index = path.join(child, 'index.html');
    if (!fs.existsSync(index)) continue;
    fs.copyFileSync(index, `${child}.html`);
    fs.unlinkSync(index);
    if (fs.readdirSync(child).length === 0) fs.rmdirSync(child);
    const route = `/${path.relative(buildDir, child).split(path.sep).join('/')}`;
    flattened.push(`${route}/ ${route} 301`);
  }
}

flatten(buildDir);
const publicRedirects = path.join(process.cwd(), 'public/_redirects');
const existing = fs.existsSync(publicRedirects) ? fs.readFileSync(publicRedirects, 'utf8').trim() : '';
fs.writeFileSync(path.join(buildDir, '_redirects'), `${existing}${existing ? '\n\n' : ''}# Generated by scripts/flatten-html.ts\n${flattened.join('\n')}\n`);
console.log(`Flattened ${flattened.length} routes`);
